apiVersion: v1
kind: Namespace
metadata:
  name: shir1
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: shir1-quota
  namespace: shir1
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
