apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-1730284256
  namespace: shir5
  annotations:
    app.kubernetes.io/instance: flask-app-1730284256
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-1730284256
  template:
    metadata:
      labels:
        app: flask-app-1730284256
        developer: shir5
    spec:
      containers:
      - name: flask-app
        image: shirbenyosef1/flask_app
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-1730284256
  namespace: shir5
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 31449  # Specify the nodePort explicitly
  selector:
    app: flask-app-1730284256
