apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-1730272418
  namespace: shir3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app-1730272418
  template:
    metadata:
      labels:
        app: flask-app-1730272418
        developer: shir3
    spec:
      containers:
      - name: flask-app
        image: shirbenyosef1/flask_app
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-1730272418
  namespace: shir3
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: flask-app-1730272418
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-app-1730272418
  namespace: shir3
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: flask-app-1730272418.shir3.apps.k3s.company.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-app-1730272418
            port:
              number: 5000
