apiVersion: v1
kind: Namespace
metadata:
  name: shir
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: shir-quota
  namespace: shir
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
