apiVersion: v1
kind: Namespace
metadata:
  name: shir5
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: shir5-quota
  namespace: shir5
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "10"
    services: "5"
